# Generated by Django 4.0.1 on 2022-07-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='fixed_deposit',
            field=models.FloatField(choices=[('one_year', 4.5), ('two_year', 3.5), ('five_year', 5.5)]),
        ),
    ]
