# Generated by Django 4.0.1 on 2022-07-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_alter_bank_bank_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='minimum_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='ownership',
            field=models.CharField(default='Private', max_length=40),
        ),
    ]
