# Generated by Django 4.0.1 on 2022-07-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0004_bank_minimum_balance_bank_ownership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='fixed_deposit',
            field=models.FloatField(blank=True, choices=[('one_year', 4.5), ('two_year', 3.5), ('five_year', 5.5)], null=True),
        ),
    ]
