# Generated by Django 4.0.1 on 2022-07-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0005_alter_bank_fixed_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='iden',
            field=models.CharField(default='identity', max_length=120),
        ),
    ]
