# Generated by Django 4.0.1 on 2022-07-13 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0007_remove_bank_fixed_deposit_fixeddeposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='saving_acc',
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='tenure',
            field=models.CharField(default='around a year', max_length=180),
        ),
        migrations.CreateModel(
            name='SavingAcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.CharField(default='10000', max_length=180)),
                ('interest', models.FloatField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.bank')),
            ],
        ),
    ]
