# Generated by Django 4.0.1 on 2022-07-14 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0009_bank_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='current_acc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SalaryAcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.CharField(default='10000', max_length=180)),
                ('interest', models.FloatField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.bank')),
            ],
        ),
    ]
