# Generated by Django 4.0.1 on 2022-07-14 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0010_alter_bank_current_acc_salaryacc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='current_acc',
        ),
    ]
