# Generated by Django 4.0.1 on 2022-07-14 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0011_remove_bank_current_acc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='rural_bank',
        ),
    ]
